version: "3"
services:
  mariadb:
    image: mariadb:10.6 # 本地 mac 使用这个版本
    container_name: ${CONTAINER_NAME}
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DATA_DIR}/mariadb:/var/lib/mysql
    #    restart: always
    # restart: ${RESTART_MODE}
    privileged: true
  redis:
    image: redis:6.2.6-alpine # 指定服务镜像，最好是与之前下载的redis配置文件保持一致
    container_name: crm-redis # 容器名称
    # restart: on-failure                                                       # 重启方式
    restart: always
    environment:
      - TZ=Asia/Shanghai # 设置时区
    volumes: # 配置数据卷
      - ${DATA_DIR}/redis:/data
      - ./conf/redis/redis.conf:/etc/redis/redis.conf
    ports: # 映射端口
      - "26379:6379"
    sysctls: # 设置容器中的内核参数
      - net.core.somaxconn=1024
    command: /bin/sh -c "echo 'vm.overcommit_memory = 1' >> /etc/sysctl.conf && redis-server /etc/redis/redis.conf --appendonly yes" # 指定配置文件并开启持久化
    privileged: true # 使用该参数，container内的root拥有真正的root权限。否则，container内的root只是外部的一个普通用户权限
